### ISSUE TITLE
Only one ERB tag an option?

### ISSUE THREAD

**Issue by johntdyer** [eddorre/SublimeERB#10]
The gif seems to show you toggling thru different ERB braces but I dont see how to do that myself, am I missing something?

**Comment by eddorre** [comment]
@johntdyer In order to toggle the ERB tags just keep pressing the key combination and it should loop through all of the ERB tags.

**Comment by johntdyer** [comment]
Nope, thats not working for me, example below from pressing the key 3 times

<%= <%= <%= test %> %> %>

**Comment by eddorre** [comment]
@johntdyer,

If you have a word highlighted it will only do it once and then do the following as you described. I'm still working on building highlighting and toggling.

If you don't have anything highlighted, then you should be able to toggle through them.
