### ISSUE TITLE
No ERB command on ubuntu?

### ISSUE THREAD

**Issue by Rio517** [eddorre/SublimeERB#11]
Hey, 

Over the past few weeks this has stopped working for me in rails files.

Oddly, if I try to call it in a plain text file or with syntax set as "Ruby," but not anything from the rails bundle, it works.  Anyone else dealing with this issue?

-Mario

**Comment by eddorre** [comment]
@Rio517 

What version of Ubuntu and Sublime Text are you using? Are you using the Package Control manager or are you installing by symlinking? One more thing, what's the extension of the file that you are using?

**Comment by Rio517** [comment]
Hey, 

I'm using the package control with Sublime build 2195, but I actually don't think it's  this package at all. I realized that my *.html.erb files are not correctly highlighted, either.

I was able to temporarily fix this issue by re-installing sublime, but then the issue came back.  I wonder if my bundle files have been corrupted.

I'll keep working at it, but you could probably close this issue.  If I find any novel information, I'll post it on this tread so others having this problem know what's up.

-Mario

**Comment by eddorre** [comment]
Mario,

I'll go ahead and close this issue, but I'm curious, is the problem still happening? If not, what was the solution?

**Comment by Rio517** [comment]
I meant to come back and write up my final solution, but forgot.   I believe that I wound up not just reinstalling sublime, but also deleting all sublimie's appdata as well.  There were some files not removed by the normal uninstall procedure.  I believe that the general issue was that the bundle files had become corrupted.

It was only ever an issue on my windows install.  Never on ubuntu.

-Mario

**Comment by eddorre** [comment]
Thanks, Mario!
