### ISSUE TITLE
Can't get it to work in OSX (10.6.8)

### ISSUE THREAD

**Issue by manu3569** [eddorre/SublimeERB#12]
manus-imac:~ manu$ python -i
Python 2.6.1 (r261:67515, Jun 24 2010, 21:47:49) 
[GCC 4.2.1 (Apple Inc. build 5646)] on darwin

Sublime 2 Build: 2181

Mac OS X 10.6.8
## 

I installed the plugin via the package manager and I see the files in ~/Library/Application Support/Sublime Text 2/Packages/ERB Insert and Toggle Commands/. I added the following to ~/Library/Application Support/Sublime Text 2/Packages/User/:

 { "keys": ["ctrl+shift+."], "command": "erb" }

Then I restarted the app, saving all files. I also tried other key combinations, but the tags are not inserted in the current file (html.erb) and it doesn't cycle through the different ERB tag types. 

Any tips?

**Comment by eddorre** [comment]
@manu3569,

What keymap file did you add that to? Default (OSX).sublime-keymap?

You can see how to set the keymap. Shown here:

<div class="thumbnail"><a href="https://skitch.com/eddorre/8a5nc/menubar"><img src="https://img.skitch.com/20120504-cued1dftc3k4i4p6umsqqdh2fp.preview.jpg" alt="Menubar" /></a><br /><span></div>


If you open the console (CTRL+`) in Sublime Text, do you see that it's loading the plugin?

**Comment by manu3569** [comment]
Yes. It's in the OSX file (sorry for missing that in my earlier post).

I also see the plugin being loaded:

Reloading plugin /Users/manu/Library/Application Support/Sublime Text 2/Packages/ERB Insert and Toggle Commands/erb_block.py

**Comment by eddorre** [comment]
@manu3569,

Click on View dropdown menu and select 'Show console' and trigger the command. Is there anything that's output there?
