### ISSUE TITLE
toggling ERB command not working

### ISSUE THREAD

**Issue by BenU** [eddorre/SublimeERB#13]
Using Sublime Text 2 Beta, Build: 2181.
Latest SublimeERB as of 2012/05/10
Mac 10.7.3

I'm a newby following the [Rails Tutorial](http://ruby.railstutorial.org/) and the [Rails Tutorial Sublime Text 2 Video](http://www.youtube.com/watch?v=05x1Jk4rT1A&feature=youtu.be)
I've got all other shortcuts and commands working, added "{ "keys": ["ctrl+shift+."], "command": "erb" } to my User Keyword Bindings and nothing happens when I type "ctrl + shift + ." or "command + shift + ."  

It is very possible that I'm making a mistake that I'm not seeing if no one else is having this problem.

**Comment by tjstankus** [comment]
Same thing here. Sublime Text console shows "no command for selector: noop:" when I hit ctrl+shift+.

**Comment by eddorre** [comment]
@BenU and @tjstankus,

Curious, did you install the plugin via Sublime Package Control? Otherwise, you can find the manual install instructions here: https://github.com/eddorre/SublimeERB

Can you try the following on a new file?, Press CMD + SHIFT + P. Then type in sethtml. You'll see Set Syntax: HTML (Rails) - select that option. Then try the key combination to insert an ERB block. Does it work?

**Comment by tjstankus** [comment]
Thanks for following up. Yes, if I recall I installed it via Package Control. Since then I've pretty much switched back to Vim. :)

**Comment by BenU** [comment]
Thanks for follow-up, Carlos.  I'll take a look at this again shortly.  In the mean time, I'm enjoying Sublime's other features.  The ability to run rspec/spork is great!

Thanks again for your work on sublime and your help here.

I'll keep you posted.

Best,
Ben

**Comment by mildfuzz** [comment]
same issue here. I tried @eddorre's instructions, no joy.

**Comment by IanRock** [comment]
Silly comment, but you need to make sure that you are inserting the keybinding between the square braces.
So if this was the only item in your user keymap it would look like this:

[
{ "keys": ["ctrl+shift+."], "command": "erb" }
]

**Comment by armhold** [comment]
@IanRock- thanks, you solved the issue for me. Just started w/ Sublime and I had no idea what the syntax of the keymap file was.... JSON perhaps?

**Comment by sathishmanohar** [comment]
Sublime Text 2 - version 2.0.1 build 2217
Ubuntu - 12.04
Sublime ERB - Latest one

keybindings doesn't work for me, I've tried all suggestions in this comment thread, tried installing via package manager and manually, both didn't work.

**Comment by politicus** [comment]
Had the same problem. 
Just changed the default shortcut. 
Now it is working.

**Comment by sohussain** [comment]
using Ubuntu - 12.04, 
installed via Package manager

followed @IanRock 's suggestion, works like a charm.

**Comment by eddorre** [comment]
I've updated the documentation to make it clear that the key mapping file is a JSON file. The README also now has JSON syntax highlighting to make this clearer.

**Comment by kermitology** [comment]
This issue appears to be back with Sublime Text 3.

**Comment by eddorre** [comment]
@kermitology,

Thanks. I'll have to download a copy of that and test against it.

**Comment by eddorre** [comment]
@kermitology,

Just downloaded the latest version of Sublime Text 3 on my Mac and followed the instructions from the README. I don't see any issues.

The install for the package manager is a bit different, but it still works when you use the latest version of that project.

Can you tell me what version you used and what OS you are using?

**Comment by kermitology** [comment]
I must have missed those installation instructions when I installed the beta. I followed them and now things are working.  

Thanks!

**Comment by Methos2013** [comment]
I have a peculiar thing happening...the toggle works for me in OS X Mountain Lion and Sublime Text 2, but instead of CMD + SHIFT + ., I have to use CTRL + SHIFT + . 

I tried changing the key binding from "ctrl" to "cmd" and back again; in all cases I still have to use the CTRL button for the toggle to work. Any ideas on why this might be?! 

Thanks in advance!

**Comment by eddorre** [comment]
@Methos2013,

What does your keybinding file look like?

**Comment by Methos2013** [comment]
Default keybinding file is blank; user keybinding file is as follows:

[
{ "keys": ["ctrl+shift+."], "command": "erb" }
]

I had the 2nd line indented, but removed the spaces just in case it might make a difference. Same behaviour either way (indented or not). Same behaviour if changed to ["cmd+shift+."], also.

**Comment by eddorre** [comment]
@Methos2013,

"ctrl+shift+." should work and that should be mapped to the command key. You haven't re-mapped that key in the keyboard preferences have you?

**Comment by Methos2013** [comment]
Nope I haven't remapped that key. Screenshot of current keyboard
assignments/defaults enclosed; hope it works to attach it to this e-mail.
If not I'll repost it in the thread on GitHub.

![keyboarddefaults](https://f.cloud.github.com/assets/4214844/1004365/d3cdcec8-0aa0-11e3-9a49-d2e27c86a857.png)

**Comment by peterkrieg** [comment]
@IanRock  I've been trying to work sublime keybindings for an hour and it was just the missing square brackets..  I couldn't figure it out until I saw this thread, so thanks for that!

**Comment by IanRock** [comment]
No probs, glad you got it working!
