### ISSUE TITLE
Cycle <% %> tags around the selection

### ISSUE THREAD

**Issue by firedev** [eddorre/SublimeERB#16]
Could you please fix it so when something is selected I could continue pressing Ctrl-Shift-. and it would cycle between <% %> tags?

Right now pressing Ctrl-Shift-. twice produces this:

<%= <%= "Hello #{world}" %> %>

**Comment by fannar** [comment]
Would be nice addition to this great plugin!

**Comment by eddorre** [comment]
@firedev and @fannar,

Yep. It's on my roadmap. Just haven't had much time lately.
