### ISSUE TITLE
SublimeERB is not in the Package Control

### ISSUE THREAD

**Issue by firedev** [eddorre/SublimeERB#17]
Just wanted to use it on another computer and couldn't find it in freshly installed Package Control, I don't know if it should be reported to you or the Package Control maintainers but here it is anyway.

**Comment by eddorre** [comment]
@firedev,

I uninstalled the package and was able to find it. Here is how I did it (I'm on a Mac, so you may need to alter the keys if you're using the Windows version or the Linux version):
1. CMD + SHIFT + P
2. Type in 'install'. You should see "Package Control: Install Package"
3. Type in erb. You should see "ERB Insert and Toggle Commands"

**Comment by firedev** [comment]
Probably was a temporary glitch in Package Control
