### ISSUE TITLE
ImportError: No module named erb_block

### ISSUE THREAD

**Issue by 13gne** [eddorre/SublimeERB#2]
After following the directions for installation (Mac OSX), key binding addition, and subsequent reload, the shortcut will not work. The ST2 console reports:

```
Unloading plugin /Users/jjuszczak/Library/Application Support/Sublime Text 2/Packages/User/erb_block.py
Reloading plugin /Users/jjuszczak/Library/Application Support/Sublime Text 2/Packages/User/erb_block.py
Traceback (most recent call last):
File "./sublime_plugin.py", line 57, in reload_plugin
ImportError: No module named erb_block
```

**Comment by eddorre** [comment]
13gne,

I uploaded some new instructions. Give that a shot and let me know how it goes.

**Comment by 13gne** [comment]
It may have been a ST2 problem. I did a clean install and your previous instructions worked. Great work.

BTW, thanks for the "removal of whitespace" update. That was bugging me.
