### ISSUE TITLE
default keybinding issue

### ISSUE THREAD

**Issue by charlieussery** [eddorre/SublimeERB#20]
Where exactly do I paste this code: { "keys": ["ctrl+shift+."], "command": "erb" } into this file?

http://chrle.us/Iefy

Everytime I paste and save I get this error: http://chrle.us/IejM

**Comment by firedev** [comment]
Try to paste the short code, everything looks correct on the screenshot btw.

**Comment by eddorre** [comment]
@charlieussery,

That should be pasted in the Key Bindings - User file. On OS X do the following:
1. Click on Sublime Text 2
2. Highlight Preferences
3. Click Key Bindings - User

Make sure that you have square brackets around your content in there as it's a json file (I've just updated the documentation for this).
