### ISSUE TITLE
ERB tags outdent

### ISSUE THREAD

**Issue by scottweisman** [eddorre/SublimeERB#24]
When I use the erb command my tags are automatically outdenting to the far left edge of Sublime. Has anyone had this issue?

**Comment by eddorre** [comment]
@scottweisman,

Can you give me an indication of what system you're on (Mac OS X, Linux or Windows and what version) and the version of Sublime Text you're using?

**Comment by scottweisman** [comment]
This actually seems to be an issue with RubyTest for Sublime. I'll post it there. Thanks.
