### ISSUE TITLE
Clarify if this is available in Package Control

### ISSUE THREAD

**Issue by abitdodgy** [eddorre/SublimeERB#25]
Perhaps I'm missing something, but the docs say to install this using Package Control, yet I can't find it on there. Is it available with Package Control or not?

**Comment by eddorre** [comment]
@abitdodgy,

What version of Sublime Text are you using?

It should look something like this:

http://monosnap.com/image/uxxXwA3Azwol75jrD3UWzgtsF.png

**Comment by AhmedAttyah** [comment]
i think it would be nice to name it SublimeERB in the package manager as well, it confused me a little bit, i thought its another plugin

**Comment by abitdodgy** [comment]
I'm using Sublime Text 2. I can confirm that this package is not available to me.

**Comment by AhmedAttyah** [comment]
actually it is available for sublime text 2 but under another name " ERB Insert and Toggle Commands" just like the image above, that is why i asked to edit package name in sublime text package manager

**Comment by abitdodgy** [comment]
Not to me, it's not. I already looked at the screen shot. "ERB Insert and Toggle Commands" produces no results. "ERB Insert" also produces no results.

**Comment by AhmedAttyah** [comment]
that is very weird i installed it today on Ubuntu and just installed it again on windows and i still find it with that name " ERB Insert and Toggle Commands"!

**Comment by eddorre** [comment]
@abitdodgy,

It should be available in package control. If you don't see it under the 'install package' command then it's probably already installed.

Look under the remove package command.

@AhmedAttyah,

I'll see what I can do about re-naming it.

**Comment by gabrielecirulli** [comment]
ST3 here. I noticed that it's only available for ST2 (says so on the package control site). Just wondering if there's gonna be a ST3 version any time in the future. It sounds like it'd be a great package to have.

**Comment by partydrone** [comment]
Same problem with a fresh install of ST3 build 3047. The package is not installed, and it doesn't show up in the list when searching for it. The only thing with "ERB" in the title is "ERB Snippets."

**Comment by bbshih** [comment]
@gabrielecirulli @partydrone I installed it manually by cloning the repo and putting the directory in (this is for OSX) 

```
/Users/user_name/Library/Application\ Support/Sublime\ Text\ 3/Packages/SublimeERB
```

Also add this to your keybindings: 

```
[
     { "keys": ["ctrl+shift+."], "command": "erb" }
]
```

It worked fine. I created a new issue(https://github.com/eddorre/SublimeERB/issues/30) asking for it to be added to the Package Control for ST3.

**Comment by eddorre** [comment]
Thanks to everyone that reported an issue here. I'm going to close this in favor of issue #30.
