### ISSUE TITLE
Inserting more ERB tags instead of cycling

### ISSUE THREAD

**Issue by niksosf** [eddorre/SublimeERB#28]
Hi there, nice package! I missed this feature very much since switch from TextMate. But I ran into some trouble: AFter a fresh install of the package, the ctrl+shift+. works as expected, toggling between different erb tags. But after restarting Sublime, whenever I hit the shortcut again, it just keep like so <%= <%= <%= <%= <%=  %> %> %> %> %> 

I am on Mac 10.8.4. SublimeText 2. I am just using the stock Ruby and Rails package provided by SublimeText. Is there anything I should check? like other installed packages?

Thanks!!

**Comment by eddorre** [comment]
@niksosf,

Is this still happening to you?

**Comment by niksosf** [comment]
Hi Carlos,

Yes, it is still happening to me. I tried removing SublimeText with AppCleaner and re-installing everything.. :(

**Comment by niksosf** [comment]
Hi Carlos,

I installed SublimeText 3 from scratch and it's working like a charm now. I don't exactly know what happened with ST2.
