### ISSUE TITLE
Whitespace around the ERB block

### ISSUE THREAD

**Issue by mitio** [eddorre/SublimeERB#3]
First off, this is a neat plugin, thanks!

I just wanted to mention that TextMate does not insert spaces around the ERB tags if there are none. Also, I, as a developer, would like to have control on that. If I want spaces on the left and/or right of the ERB block, I'll just insert them manually, position the cursor and then insert the ERB block.

What do you think about removing this whitespace insertion check?

**Comment by mitio** [comment]
Hey, @eddorre, anything on this?

**Comment by eddorre** [comment]
Mitio,

Just committed a change that should fix that.

**Comment by mitio** [comment]
Works like a charm!

Thanks, man!
