### ISSUE TITLE
Sublime Text 3 support

### ISSUE THREAD

**Issue by bbshih** [eddorre/SublimeERB#30]
I manually installed this to Sublime Text 3 and it worked fine. Any reason to keep it from being included in Package Control for ST3?

I noticed it's here:
     https://github.com/wbond/package_control_channel/blob/cff9d72fb94438e1e4b195511eed84aa16b4dc8b/repository/e.json

with:

```
 "sublime_text": "<3000"
```

**Comment by demisx** [comment]
Same here, the "ERB Insert and Toggle Commands" do not show up in Package Control under ST3 beta, though readme says it should. Have to install manually.

Also, can you please rename the package to "SublimeERB"? Having two different names is confusing.

**Comment by eddorre** [comment]
@bbshih and @colddata What version of Sublime Text 3 are you using?

**Comment by bbshih** [comment]
Build 3047

**Comment by demisx** [comment]
Build 3047 on Mountain Lion OS 10.8.5

**Comment by mbrichman** [comment]
I also confirm that it doesn't show up in Package Control in 3047. I was able to install manually and get it to work.

A note though: It doesn't work if you install it into Packages/User. However, if you install into the Packages directory itself, it does work.

**Comment by eddorre** [comment]
Was able to duplicate this myself. It looks like the repository for the Package Control Channel needed to be updated. To include both Sublime Text 2 and 3.

I've submitted a pull request to that channel here:

https://github.com/wbond/package_control_channel/pull/2086

NOTE: That this renames the package to SublimeERB to match my repository name. I've included metadata that should update the package for you (so says the Package Control Channel documentation).

Hopefully this gets merged in soon.

**Comment by demisx** [comment]
Awesome. Thanks for renaming it as well. Much more clearer this way.

**Comment by eddorre** [comment]
This has been merged into the package control channel.

**Comment by demisx** [comment]
I've removed manual install and re-added SublimeErb via Package Control now. Everything went smoothly, except that my `Ctrl+Shift+.` user key binding stopped working. I had it before as:

```
{ "keys": ["ctrl+shift+."], "command": "erb", "context":
      [
        { "key": "selector", "operator": "equal", "operand": "text.html.ruby, text.haml, source.yaml, source.css, source.scss, source.js, source.coffee" }
      ]
    }
```

I had to replace it with:

```
{ "keys": ["ctrl+shift+."], "command": "erb" }
```

to make it work again.
