### ISSUE TITLE
Rearrange output in order of importance

### ISSUE THREAD

**Issue by caged** [eddorre/SublimeERB#5]
Consider this a feature request, but I'd like to request merging this patch:
https://github.com/fcoury/SublimeERB/commit/27440c18cf7fec08c9cffb4bfaee3ae201f6db87

Right now the order seems arbitrary.  The two most common erb blocks are output and no output.  Currently no output takes 4 keystrokes, it's behind ERB comments which are a lot more rare.

**Comment by eddorre** [comment]
Justin,

I've made this change. I think I had those in the previous order for testing and I never went back to Textmate to see how those were being generated. It's been in the back of my mind for a while.

**Comment by caged** [comment]
Awesome!
