### ISSUE TITLE
README error?

### ISSUE THREAD

**Issue by antunderwood** [eddorre/SublimeERB#7]
Should the git clone command be

git clone git://github.com/eddorre/SublimeERB.git ~/.sublime_erb

rather than

git clone git@github.com:eddorre/SublimeERB.git ~/.sublime_erb

**Comment by eddorre** [comment]
@aunderwo,

That's the SSH link (according to GitHub). I just used the default link that is copied when copying the URL for the project.

Either one of those should work:

`git@github.com:eddorre/SublimeERB.git`
`https://eddorre@github.com/eddorre/SublimeERB.git`
`git://github.com/eddorre/SublimeERB.git`

**Comment by antunderwood** [comment]
Thanks.
For some reason communicating with github on 8752(the port for git@github.com) failed for me but not via git://github.com using port 9418. Maybe a firewall/proxy issue at my end.
